### PR TITLE
Henson

### PR DESCRIPTION
**Pull request by mrzv**
Fixup Henson stuff on Linux.

### CODE REVIEW

**Comment by mrzv** [comment]
@zarija Do you want me to move the `.chai` scripts to `Exec/Henson`?

**Comment by asalmgren** [comment]
I would like to keep LyA itself relatively "clean" so I would prefer having
the .chai scripts in a separate Exec folder.  We can have a LyA_henson for
example.

**Comment by mrzv** [comment]
I'll move chai scripts into `Exec/Henson`, which already exists with different sample/auxiliary puppets. Other than that, the only change in `Exec/LyA` is `USE_HENSON = FALSE` in `GNUmakefile`. So I'm not sure it makes sense to create a separate `LyA_henson` directory. I think it would only create maintenance overhead.

**Comment by zarija** [comment]
Yep, all good.  All Henson stuff should goe into Exec/Henson, only USE_HENSON = FALSE stays in the GNUmakefile of LyA.

**Pull request merged**
